package com.example.groupassignment.SImpleRAG;

import com.example.groupassignment.Query.QueryController;
import com.example.groupassignment.User.UserLoginController;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class ChatbotController {


    @FXML
    private VBox chatBox;
    @FXML
    private TextField inputField;
    @FXML
    private Button sendButton;
    @FXML
    private ScrollPane chatScroll;


    @FXML
    private void handleSend() {
        String question = inputField.getText();
        if (question == null || question.isBlank()) return;

        addUserBubble(question);
        inputField.clear();
        sendButton.setDisable(true);

        LangChainChat langChainChat = new LangChainChat();
        CompletableFuture<String> replyFuture = CompletableFuture.supplyAsync(() -> langChainChat.LangChainPipeline(question));

        replyFuture.whenComplete((answer, ex) -> {
            Platform.runLater(() -> {
                if (ex != null) {
                    addBotBubble("Error: " + ex.getMessage());
                } else {
                    addBotBubble(answer);
                }
                sendButton.setDisable(false);
                chatScroll.layout();
                chatScroll.setVvalue(1.0);
            });
        });
    }

    private void addUserBubble(String text) {
        Label lbl = new Label(text);
        lbl.setWrapText(true);
        lbl.setMaxWidth(400);
        lbl.setStyle("-fx-background-color: #4CAF50; -fx-text-fill: white; -fx-padding: 8 12 8 12; -fx-background-radius: 8;");
        HBox box = new HBox(lbl);
        box.setStyle("-fx-alignment: center-right;");
        chatBox.getChildren().add(box);
    }

    private void addBotBubble(String text) {
        Label lbl = new Label(text);
        lbl.setWrapText(true);
        lbl.setMaxWidth(400);
        lbl.setStyle("-fx-background-color: #dddddd; -fx-text-fill: black; -fx-padding: 8 12 8 12; -fx-background-radius: 8;");
        HBox box = new HBox(lbl);
        box.setStyle("-fx-alignment: center-left;");
        chatBox.getChildren().add(box);
    }

    @FXML
    private void ForwardQuery() throws IOException {
        //for forwarding the query to admin
        //take the most recent chat from chatbox and forward it to QueryJson file thingu with user details
        //ex : (Username) forwarded a query because they couldnt find " (most recent chat)"
        //format will be:
        //QueryID: autogenerated
        //Username: current logged in user
        //Reason: take ex


        //lwk remove these


        //find most recent user message
        List<Node> children = chatBox.getChildren();
        HBox lastMatch = null;
        for (int i = children.size() - 1; i >= 0; i--) {
            Node n = children.get(i);
            if (n instanceof HBox hBox && !hBox.getChildren().isEmpty()) {
                Node firstChild = hBox.getChildren().getFirst();
                if (firstChild instanceof Label lbl && lbl.getStyle().contains("#4CAF50")) {
                    lastMatch = hBox; // not a label, skip
                }
            }
        }
        if (lastMatch != null) {
            System.out.println("Entered Forwarding");
            Label lbl = (Label) lastMatch.getChildren().getFirst();
            String recentUserMessage = lbl.getText();
            //forward to admin panel
            QueryController.receiveQuery(UserLoginController.user, recentUserMessage);
        } else {
            System.out.println("No user message found to forward.");
        }
    }
    @FXML
    protected void Back(ActionEvent event) throws IOException {
        Parent root = FXMLLoader.load(getClass().getResource("/com/example/groupassignment/KB/KnowledgeBaseSearch.fxml"));
        Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        Scene scene = new Scene(root);
        stage.setScene(scene);
        stage.show();
    }
}
